aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 561903439674.dkr.ecr.eu-north-1.amazonaws.comjkj#!/bin/bash
set -e

IMAGE_NAME="pagamipana-ocr-lambda-python"
TAG="latest"

echo "🐳 Building Docker image for AWS Lambda (Python)..."
docker build -f Dockerfile.lambda.python -t ${IMAGE_NAME}:${TAG} .

echo ""
echo "✅ Docker image built successfully!"
echo ""
echo "📦 Image: ${IMAGE_NAME}:${TAG}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Pasos siguientes para desplegar en AWS Lambda:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPCIÓN 1: Subir a Amazon ECR y crear Lambda desde portal"
echo ""
echo "1. Crear repositorio en ECR:"
echo "   - Ve a: https://console.aws.amazon.com/ecr"
echo "   - Click 'Create repository'"
echo "   - Name: ${IMAGE_NAME}"
echo "   - Click 'Create'"
echo ""
echo "2. Autenticarse en ECR (copia el comando desde el portal ECR > 'View push commands')"
echo "   aws ecr get-login-password --region us-east-1 | \\"
echo "     docker login --username AWS --password-stdin <tu-account-id>.dkr.ecr.us-east-1.amazonaws.com"
echo ""
echo "3. Etiquetar la imagen:"
echo "   docker tag ${IMAGE_NAME}:${TAG} <tu-account-id>.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}:${TAG}"
echo ""
echo "4. Subir a ECR:"
echo "   docker push <tu-account-id>.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}:${TAG}"
echo ""
echo "5. Crear función Lambda desde el portal:"
echo "   - Ve a: https://console.aws.amazon.com/lambda"
echo "   - Click 'Create function'"
echo "   - Selecciona 'Container image'"
echo "   - Function name: pagamipana-ocr-python"
echo "   - Container image URI: <pega la URI de ECR>"
echo "   - Click 'Create function'"
echo ""
echo "6. Configurar la función:"
echo "   - Configuration > Environment variables"
echo "   - Añade: GEMINI_API_KEY = tu-api-key"
echo "   - Configuration > General configuration"
echo "   - Timeout: 60 segundos"
echo "   - Memory: 512 MB"
echo ""
echo "7. Crear Function URL:"
echo "   - Configuration > Function URL"
echo "   - Click 'Create function URL'"
echo "   - Auth type: NONE"
echo "   - Configure CORS: Enable, Allow origin: *, Allow methods: GET, POST, OPTIONS"
echo "   - Click 'Save'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPCIÓN 2: Test local primero"
echo ""
echo "   python -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install -r requirements.txt"
echo "   GEMINI_API_KEY=tu-api-key python main.py"
echo ""
echo "   # Probar:"
echo "   curl http://localhost:8080/health"
echo ""
