FROM public.ecr.aws/lambda/python:3.12

# Copiar requirements
COPY requirements.txt ${LAMBDA_TASK_ROOT}/

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY main.py ${LAMBDA_TASK_ROOT}/

# Handler
CMD ["main.lambda_handler"]
